HAN-112: servicio de autenticación
Hanagotchi/users pull request #27
Opened 2024-05-30 03:07 UTC by violetaperezandrade

se agrego un endpoint `POST /users/token` que en el body recibe un token y como response devuelte el siguiente body:
```
{
    "user_id": <user_id>
}
```

2024-06-04 03:43 UTC, fjpacheco requested changes

2024-06-04 03:43 UTC, fjpacheco commented on app/service/Users.py
> +        decoded_token = jwt.decode(token,
clavar un try except aca 

<img width="983" alt="image" src="https://github.com/Hanagotchi/users/assets/51347305/ad81b987-5250-4f78-a8e7-d80ead52f7e6">

sino rompe si le mando un token inexistente

2024-06-04 04:33 UTC, violetaperezandrade commented on app/service/Users.py
> +        decoded_token = jwt.decode(token,
https://github.com/Hanagotchi/users/pull/14#issuecomment-2075121905

Como las requests pasan primero por el gateway se asume que el token esxiste ademas de ser valido porque se chequea ahi

2024-06-06 01:17 UTC, fjpacheco approved these changes

2024-06-12 03:26 UTC, Agustinefe approved these changes

2024-06-17 02:18 UTC, merged