HAN-72: add location field
Hanagotchi/users pull request #7
Opened 2024-04-01 05:40 UTC by feijooso

2024-04-01 13:10 UTC, Agustinefe requested changes

2024-04-01 13:10 UTC, Agustinefe commented on app/docker/tablas.sql
> +    ('Sofi', 'sofi@fi.uba.ar', '{"lat": 1190, "long": 500}'),
Habria que agregar unas constraints para que la latitud este entre [-90, 90] y la longitud entre [-180, 180]

Por otra parte, los campos aceptan numeros con decimales? o solo enteros?

2024-04-02 18:54 UTC, Agustinefe commented on app/docker/tablas.sql
> +    users_service.users (name, email, birthdate, location)
Cambio el request changes por un comment:

Habria que validar en Service que la latitud esta entre [-90, 90] y la longitud entre [-180. 180]. La validacion tambien podria estar en el schema, usando un Field y definiendole un gt y lt

2024-04-02 18:54 UTC, Agustinefe approved these changes

2024-04-03 21:26 UTC, fjpacheco approved these changes

2024-04-04 12:43 UTC, merged

2024-04-05 20:45 UTC, violetaperezandrade commented on app/docker/tablas.sql
> +    ('Violeta', 'violeta@fi.uba.ar', TO_DATE('1998-05-12', 'YYYY-MM-DD'), '{"lat": 330, "long": 2333}');
🥲🥲🥲